---
- name: create gerrit installation directory
  file:
    path: "{{ gerrit_warfile_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  notify: start mariadb

- name: downloading gerrit
  get_url:
    url: "{{ gerrit_dl_url }}/{{ gerrit_dl_filename }}"
    dest: "{{ gerrit_warfile_dir }}/{{ gerrit_dl_filename }}"
    sha256sum: "{{ gerrit_dl_sha256sum }}"
    validate_certs: no

- name: create gerrit group
  group:
    name: "{{ gerrit_account_group }}"
    system: yes
    state: present

- name: create gerrit user
  user:
    name: "{{ gerrit_account_user }}"
    comment: "{{ gerrit_account_comment }}"
    home: "{{ gerrit_account_home }}"
    group: "{{ gerrit_account_group }}"
    password: "{{ gerrit_account_pass }}"
    generate_ssh_key: yes
    system: yes
    state: present

- name: change gerrit.war file owner
  file:
    path: "{{ gerrit_warfile_dir }}/{{ gerrit_dl_filename }}"
    owner: "{{ gerrit_account_user }}"
    group: "{{ gerrit_account_group }}"
    mode: 0644

- name: create {{ gerrit_db }} MySQL db
  mysql_db:
    name: "{{ gerrit_db }}"
    state: present

- name: create MySQL db {{ gerrit_db_user }} user
  mysql_user:
    name: "{{ gerrit_db_user }}"
    password: "{{ gerrit_db_pass }}"
    priv: "{{ gerrit_db }}.*:ALL"
    state: present

- name: create gerrit site directory
  file:
    path: "{{ gerrit_install_dir }}"
    owner: "{{ gerrit_account_user }}"
    group: "{{ gerrit_account_group }}"
    mode: 0755
    state: directory

- name: create gerrit etc directory
  file:
    path: "{{ gerrit_install_dir }}/etc"
    owner: "{{ gerrit_account_user }}"
    group: "{{ gerrit_account_group }}"
    mode: 0755
    state: directory

- name: configuring gerrit
  template: 
    src: gerrit.config
    dest: "{{ gerrit_install_dir }}/etc/gerrit.config"
    mode: "0644"
    owner: "{{ gerrit_account_user }}"
    group: "{{ gerrit_account_group }}"

- name: configuring gerrit secure settings
  template:
    src: secure.config
    dest: "{{ gerrit_install_dir }}/etc/secure.config"
    owner: "{{ gerrit_account_user }}"
    group: "{{ gerrit_account_group }}"
    mode: "0600"

- name: initializing gerrit
  sudo_user: "{{ gerrit_account_user }}"
  command: "{{ gerrit_init }}"
  args:
    creates: "{{ gerrit_install_dir }}/bin/gerrit.sh"

- name: installing mysql connector
  get_url:
    url: "{{ gerrit_mysql_connector_url }}/{{ gerrit_mysql_connector_file }}"
    dest: "{{ gerrit_install_dir }}/lib/{{ gerrit_mysql_connector_file }}"
  sudo_user: "{{ gerrit_account_user }}"

- name: configure gerrit default service settings 
  template:
    src: gerritcodereview
    dest: /etc/default/gerritcodereview
    owner: root
    group: root
    mode: 0644

- name: configure gerrit init file link
  file:
    src: "{{ gerrit_install_dir }}/bin/gerrit.sh"
    dest: /etc/init.d/gerrit
    state: link
    
- name: configure gitweb conf-available
  template:
    src: conf-gitweb.conf
    dest: /etc/apache2/conf-available/gitweb.conf
    owner: root
    group: root
    mode: 0644

- name: configure gitweb conf-enabled
  file:
    src: /etc/apache2/conf-available/gitweb.conf
    dest: /etc/apache2/conf-enabled/gitweb.conf
    state: link
  
- name: configuring gitweb /etc/gitweb.conf
  template:
    src: etc-gitweb.conf
    dest: /etc/gitweb.conf
    owner: root
    group: root
    mode: 0644

- name: configure gitweb enable apache2 modules
  apache2_module:
    name: cgid
    state: present
  notify: restart apache2
  notify: restart gerrit
  